[build]
  publish = "public"
  command = "hugo"

[build.processing]
  skip_processing = true
  
[context.production.environment]
  HUGO_VERSION = "0.39"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.39"
  
